# Generated by Django 4.2.5 on 2023-09-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='projets_images/')),
                ('date_de_creation', models.DateTimeField(auto_now_add=True)),
                ('client', models.CharField(max_length=100)),
                ('categorie', models.CharField(choices=[('webApp', 'Web Application'), ('mobileApp', 'Mobile Application'), ('programation4.0', 'Programmation 4.0')], max_length=50)),
                ('slug', models.SlugField(editable=False, max_length=100, unique=True)),
            ],
        ),
    ]
